# USB PD Specification Parser Configuration
# Copy this file to application.yml and customize as needed

# Input PDF file path
pdf_input_file: "assets/usb_pd_spec.pdf"

# Output directory for generated files
output_directory: "outputs"

# Output JSONL file name
toc_file: "outputs/usb_pd_spec.jsonl"

# Enable OCR fallback for scanned PDFs (slower but more accurate)
ocr_fallback: true

# Maximum pages to process (null for all pages - default behavior)
# Set to a number to limit processing for testing: max_pages: 50
max_pages: null

# Logging configuration
log_level: "INFO"

# Parser settings
parser:
  # Minimum line length to consider for TOC parsing
  min_line_length: 5
  
  # Enable deduplication of TOC entries
  deduplicate: true

# Validation settings
validation:
  # Check for duplicate section IDs
  check_duplicates: true
  
  # Check for out-of-order page numbers
  check_order: true