# USB PD Specification Parser - Application Configuration
# USB PD Specification Parser Configuration

# Input PDF file path
pdf_input_file: "assets/USB_PD_R3_2 V1.1 2024-10.pdf"

# Output directory
output_directory: "outputs"

# Output JSONL file
toc_file: "outputs/usb_pd_spec.jsonl"

# OCR fallback
ocr_fallback: true

# Max pages to process (null for all pages)
max_pages: null