version: '3.8'

services:
  usb-pd-parser:
    build: .
    container_name: usb-pd-parser
    volumes:
      - ./assets:/app/assets:ro
      - ./outputs:/app/outputs
      - ./application.yml:/app/application.yml:ro
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    command: ["python", "main.py"]
    
  # Development service with hot reload
  usb-pd-parser-dev:
    build: 
      context: .
      target: base
    container_name: usb-pd-parser-dev
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    command: ["python", "main.py", "--debug"]
    profiles:
      - dev

  # Test runner service
  test-runner:
    build:
      context: .
      target: base
    container_name: usb-pd-parser-test
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["pytest", "tests/", "-v", "--cov=src"]
    profiles:
      - test