version: '3.8'

services:
  usb-pd-parser:
    build: .
    volumes:
      - ./assets:/app/assets:ro
      - ./outputs:/app/outputs
      - ./application.yml:/app/application.yml:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py --input assets/sample.pdf --out outputs/docker_output.jsonl --debug

  # Development service with mounted source code
  usb-pd-parser-dev:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py --help
    profiles:
      - dev