[tool.black]
line-length = 88
target-version = ['py39']

[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP"]
ignore = [
    "E501",  # Line too long (handled by black)
    "F401",  # Unused imports (handled by IDE)
    "UP035", # typing.Dict -> dict (keep for compatibility)
]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
strict_optional = false
warn_return_any = false