"""Minimal report generator with OOP principles."""

from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, ClassVar

from src.config.constants import MIN_CONTENT_THRESHOLD
from src.utils.mixins import OutputDirMixin


class BaseReportGenerator(OutputDirMixin, ABC):
    """Template-method base class for report generators."""

    report_type: ClassVar[str] = "base"
    file_extension: ClassVar[str] = ""

    def __init__(self, output_dir: Path):
        super().__init__(output_dir)
        self._metadata: dict[str, Any] = {}
        self._generation_count = 0
        self._last_generated: Path | None = None

    def generate(self, data: dict[str, Any]) -> Path:
        """Generate a report file using the subclass implementation."""
        self._before_generate()
        output_path = self._render(data)
        self._after_generate(output_path)
        return output_path

    @abstractmethod
    def _render(self, data: dict[str, Any]) -> Path:
        """Subclasses implement actual report rendering."""

    def process(self, data: dict[str, Any]) -> Path:
        """Process a report with explicit data."""
        return self.generate(data)

    def validate(self) -> bool:
        """Validate that the destination directory exists."""
        return self.output_dir.exists()

    def transform(self, data: Any) -> Any:
        """Allow subclasses to transform input data when relevant."""
        raise NotImplementedError(f"{self.__class__.__name__} must override transform().")

    def serialize(self) -> str:
        """Serialize stored metadata for diagnostics."""
        return str(self._metadata)

    @property
    def output_dir(self) -> Path:
        """Expose the configured output directory."""
        return super().output_dir

    @property
    def generation_count(self) -> int:
        """Number of reports generated by this instance."""
        return self._generation_count

    @property
    def last_generated_file(self) -> Path | None:
        """Most recent generated report path."""
        return self._last_generated

    def get_report_type(self) -> str:
        """Return the concrete report type identifier."""
        if self.report_type == "base":
            raise NotImplementedError("Concrete report generators must define report_type.")
        return self.report_type

    def get_file_extension(self) -> str:
        """Return the file extension for this report type."""
        if not self.file_extension:
            raise NotImplementedError("Concrete report generators must define file_extension.")
        return self.file_extension

    def _before_generate(self) -> None:
        """Lifecycle hook executed before rendering begins."""
        self._metadata.clear()
        self._generation_count += 1

    def _after_generate(self, file_path: Path) -> None:
        """Lifecycle hook executed after rendering completes."""
        self._last_generated = file_path

    def _add_metadata(self, key: str, value: Any) -> None:
        """Store metadata for later inspection."""
        self._metadata[key] = value

    def _get_metadata(self, key: str, default: Any = None) -> Any:
        """Retrieve stored metadata."""
        return self._metadata.get(key, default)

    def _determine_validation_status(self, data: dict[str, Any]) -> str:
        """Compute and record the validation status for shared use."""
        status = (
            "PASS"
            if data.get("content_items", 0) > MIN_CONTENT_THRESHOLD
            else "FAIL"
        )
        self._add_metadata("validation_status", status)
        return status

    def __str__(self) -> str:
        return f"{self.__class__.__name__}({self.output_dir.name})"

    def __call__(self, data: dict[str, Any]) -> Path:
        return self.generate(data)


class ReportFactory:
    """Registry-backed factory for report generators."""

    _REGISTRY: dict[str, type[BaseReportGenerator]] = {}
    _INSTANCE_CACHE: dict[tuple[str, Path], BaseReportGenerator] = {}

    @classmethod
    def register(cls, key: str, generator: type[BaseReportGenerator]) -> None:
        """Register or replace a report generator implementation."""
        cls._REGISTRY[key.lower()] = generator

    @classmethod
    def create_generator(cls, report_type: str, output_dir: Path) -> BaseReportGenerator:
        """Instantiate a report generator of the requested type."""
        key = report_type.strip().lower()
        if not key:
            raise ValueError("Report type must be a non-empty string.")
        try:
            generator_cls = cls._REGISTRY[key]
        except KeyError as exc:
            available = ", ".join(sorted(cls._REGISTRY))
            raise ValueError(
                f"Unknown report type: {report_type}. Available types: {available}"
            ) from exc
        return generator_cls(output_dir)

    @classmethod
    def get_supported_types(cls) -> set[str]:
        """Return the registered report types."""
        return set(cls._REGISTRY.keys())

    @classmethod
    def create_cached_generator(cls, report_type: str, output_dir: Path) -> BaseReportGenerator:
        """Return a cached generator instance keyed by type and output directory."""
        cache_key = (report_type.strip().lower(), output_dir)
        if cache_key not in cls._INSTANCE_CACHE:
            cls._INSTANCE_CACHE[cache_key] = cls.create_generator(report_type, output_dir)
        return cls._INSTANCE_CACHE[cache_key]

    @classmethod
    def clear_cache(cls) -> None:
        """Clear any cached generator instances."""
        cls._INSTANCE_CACHE.clear()

    @classmethod
    def _get_cache_size(cls) -> int:
        """Return the number of cached instances (primarily for diagnostics)."""
        return len(cls._INSTANCE_CACHE)



