name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic PyMuPDF pdfplumber PyYAML click
          pip install pytest black ruff mypy

      - name: Format check with Black
        run: black --check .

      - name: Lint check with Ruff
        run: ruff check src tests

      - name: Type check with MyPy
        run: mypy src --ignore-missing-imports
        continue-on-error: true

      - name: Create placeholder outputs
        run: |
          mkdir -p outputs
          touch outputs/usb_pd_content.jsonl outputs/usb_pd_spec.jsonl outputs/usb_pd_toc.jsonl outputs/parser.log

      - name: Test with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q --tb=short
        continue-on-error: true

      - name: Run performance benchmark
        run: |
          python benchmarks/run_benchmark.py
        continue-on-error: true
